server:
  port: 9000
spring:
  application:
    name: gso-assignment
  datasource:
    url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false